// Generated by CoffeeScript 1.9.1
(function() {
  var c;

  c = casper;

  c.test.begin('Intergas Order test', 2, function(test) {
    c.start('http://localhost:8000');
    c.then(function() {
      test.assertTitle('GASISTA FELICE', 'Main page loaded');
      this.fill('form', {
        username: 'admin',
        password: 'lJgistcZsVnQV2M'
      }, true);
    });
    c.then(function() {
      test.assertTitle('GF - Gestione des', 'Logged user page loaded');
    });
    c.thenEvaluate(function() {
      $('#user_to_simulate').val('3');
      $('#user_to_simulate').change();
    });
    c.thenOpen('http://localhost:8000/gasistafelice/rest/#rest/gas/11');
    c.thenEvaluate(function() {
      document.querySelector('a[title=orders]'.click());
    });
    c.then(function() {
      return c.waitForSelector('.block_action');
    });
    c.thenEvaluate(function() {
      $('.block_action').click();
    });
    c.then(function() {
      this.fill('#gassupplierorder_form', {
        pact: '15',
        datetime_start_0: '24/02/2015',
        datetime_start_1: '18:00',
        datetime_end_0: '07/03/2015',
        datetime_end_1: '18:00',
        delivery_datetime_0: '10/03/2015',
        delivery_datetime_1: '20:00',
        referrer_person: '5',
        repeat_order: 'on',
        repeat_frequency: '28',
        repeat_until_date: '24/05/2015',
        intergas: 'on',
        intergas_grd: '16'
      }, true);
    });
    c.run(function() {
      test.done();
    });
  });

}).call(this);
